[package]
name = "cncli"
version = "0.0.1"
edition = "2021"
description = "Command line cyphernode helper"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.1"
clap = "2.25.1"
